### ISSUE TITLE
Python solutions for Bit manupulation

### ISSUE THREAD

**Issue by user9747** [fosscellcet/Competitive-Coding-Repository#4]
Add python implementation of the problems in Bit Manupulation

**Comment by balvinderz** [comment]
hello , i would like to do this.

**Comment by rwithik** [comment]
@balvinderz Go ahead. Be sure to read the [contibuting guidelines](https://github.com/fosscellcet/Competitive-Coding-Repository/blob/master/CONTRIBUTING.md) :)

**Comment by balvinderz** [comment]
PR #5
